version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  relay: pipes

http:
  address: "0.0.0.0:8000"
  max_request_size: 256
  middleware:
    - gzip
    - static
    - headers
  headers:
    response:
      X-Content-Type-Options: nosniff
      X-Frame-Options: SAMEORIGIN
  static:
    dir: "/var/www/html/public"
    forbid:
      - .php
      - .htaccess
  uploads:
    forbid:
      - .php
      - .exe
      - .bat
      - .sh
  pool:
    allocate_timeout: 10s
    destroy_timeout: 10s
    supervisor:
      max_worker_memory: 256
      exec_ttl: 60s

logs:
  mode: production
  level: warn
  encoding: json
  output: stdout
  err_output: stderr

status:
  address: "0.0.0.0:8080"
