[supervisord]
nodaemon=true
user=%(ENV_USER)s
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:octane]
process_name=%(program_name)s_%(process_num)s
command=php %(ENV_ROOT)s/artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8000 --rpc-port=6001 --rr-config=%(ENV_ROOT)s/.rr.yaml
user=%(ENV_USER)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
environment=LARAVEL_OCTANE="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:horizon]
process_name=%(program_name)s_%(process_num)s
command=php %(ENV_ROOT)s/artisan horizon
user=%(ENV_USER)s
autostart=%(ENV_WITH_HORIZON)s
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=3600
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scheduler]
process_name=%(program_name)s_%(process_num)s
command=supercronic -overlapping /etc/supercronic/laravel
user=%(ENV_USER)s
autostart=%(ENV_WITH_SCHEDULER)s
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:reverb]
process_name=%(program_name)s_%(process_num)s
command=php %(ENV_ROOT)s/artisan reverb:start --host=0.0.0.0
user=%(ENV_USER)s
autostart=%(ENV_WITH_REVERB)s
autorestart=true
stopasgroup=true
killasgroup=true
minfds=10000
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[include]
files=/etc/supervisord.conf
