[supervisord]
nodaemon=true
user=%(ENV_USER)s
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:horizon]
process_name=%(program_name)s_%(process_num)s
command=php %(ENV_ROOT)s/artisan horizon
user=%(ENV_USER)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=3600
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[include]
files=/etc/supervisord.conf
